version: "3.8"

services:
  postgresql:
    # build:
    #     context: .
    #     dockerfile: Dockerfile.postgresql
    image: pedrodss/custom-postgresql:v1.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mydatabasepassword}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - star

  adminer:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.adminer
    image: pedrodss/custom-adminer:v1.0
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - star

volumes:
  db_data:

networks:
  star:
    driver: bridge